Downloading/unpacking GDAL
  Running setup.py egg_info for package GDAL
    
    Could not run gdal-config!!!!
Requirement already satisfied (use --upgrade to upgrade): chardet==1.0.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): brewery==0.6 in /Library/Python/2.7/site-packages
Installing collected packages: GDAL
  Running setup.py install for GDAL
    Could not run gdal-config!!!!
    building 'osgeo._gdal' extension
    llvm-gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I../../port -I../../gcore -I../../alg -I../../ogr/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.7-intel-2.7/extensions/gdal_wrap.o
    cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
    extensions/gdal_wrap.cpp:2813:22: error: cpl_port.h: No such file or directory
    extensions/gdal_wrap.cpp:2814:24: error: cpl_string.h: No such file or directory
    extensions/gdal_wrap.cpp:2815:27: error: cpl_multiproc.h: No such file or directory
    extensions/gdal_wrap.cpp:2817:18: error: gdal.h: No such file or directory
    extensions/gdal_wrap.cpp:2818:23: error: gdal_priv.h: No such file or directory
    extensions/gdal_wrap.cpp:2819:22: error: gdal_alg.h: No such file or directory
    extensions/gdal_wrap.cpp:2820:24: error: gdalwarper.h: No such file or directory
    extensions/gdal_wrap.cpp:2837: error: expected initializer before ‘VeryQuietErrorHandler’
    extensions/gdal_wrap.cpp:2713: warning: ‘swig_module’ defined but not used
    cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
    extensions/gdal_wrap.cpp:2813:22: error: cpl_port.h: No such file or directory
    extensions/gdal_wrap.cpp:2814:24: error: cpl_string.h: No such file or directory
    extensions/gdal_wrap.cpp:2815:27: error: cpl_multiproc.h: No such file or directory
    extensions/gdal_wrap.cpp:2817:18: error: gdal.h: No such file or directory
    extensions/gdal_wrap.cpp:2818:23: error: gdal_priv.h: No such file or directory
    extensions/gdal_wrap.cpp:2819:22: error: gdal_alg.h: No such file or directory
    extensions/gdal_wrap.cpp:2820:24: error: gdalwarper.h: No such file or directory
    extensions/gdal_wrap.cpp:2837: error: expected initializer before ‘VeryQuietErrorHandler’
    extensions/gdal_wrap.cpp:2713: warning: ‘swig_module’ defined but not used
    lipo: can't open input file: /var/tmp//ccVHbhm3.out (No such file or directory)
    error: command 'llvm-gcc-4.2' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/Users/jatorre/workspace/cartodb-importer/build/GDAL/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-nBs5R2-record/install-record.txt:
    running install

running build

running build_py

running build_ext

Could not run gdal-config!!!!

building 'osgeo._gdal' extension

llvm-gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I../../port -I../../gcore -I../../alg -I../../ogr/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.7-intel-2.7/extensions/gdal_wrap.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

extensions/gdal_wrap.cpp:2813:22: error: cpl_port.h: No such file or directory

extensions/gdal_wrap.cpp:2814:24: error: cpl_string.h: No such file or directory

extensions/gdal_wrap.cpp:2815:27: error: cpl_multiproc.h: No such file or directory

extensions/gdal_wrap.cpp:2817:18: error: gdal.h: No such file or directory

extensions/gdal_wrap.cpp:2818:23: error: gdal_priv.h: No such file or directory

extensions/gdal_wrap.cpp:2819:22: error: gdal_alg.h: No such file or directory

extensions/gdal_wrap.cpp:2820:24: error: gdalwarper.h: No such file or directory

extensions/gdal_wrap.cpp:2837: error: expected initializer before ‘VeryQuietErrorHandler’

extensions/gdal_wrap.cpp:2713: warning: ‘swig_module’ defined but not used

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

extensions/gdal_wrap.cpp:2813:22: error: cpl_port.h: No such file or directory

extensions/gdal_wrap.cpp:2814:24: error: cpl_string.h: No such file or directory

extensions/gdal_wrap.cpp:2815:27: error: cpl_multiproc.h: No such file or directory

extensions/gdal_wrap.cpp:2817:18: error: gdal.h: No such file or directory

extensions/gdal_wrap.cpp:2818:23: error: gdal_priv.h: No such file or directory

extensions/gdal_wrap.cpp:2819:22: error: gdal_alg.h: No such file or directory

extensions/gdal_wrap.cpp:2820:24: error: gdalwarper.h: No such file or directory

extensions/gdal_wrap.cpp:2837: error: expected initializer before ‘VeryQuietErrorHandler’

extensions/gdal_wrap.cpp:2713: warning: ‘swig_module’ defined but not used

lipo: can't open input file: /var/tmp//ccVHbhm3.out (No such file or directory)

error: command 'llvm-gcc-4.2' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/Users/jatorre/workspace/cartodb-importer/build/GDAL/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-nBs5R2-record/install-record.txt failed with error code 1
Storing complete log in /Users/jatorre/.pip/pip.log
